In [1]:
import numpy as np
import pandas as pd

In [31]:
a = int(input('Mulai: '))
b = int(input('Selesai: '))
c = int(input('Banyak data: '))

data = np.random.randint(a, b, c)

Mulai: 1
Selesai: 51
Banyak data: 40


In [37]:
data

array([ 3,  5,  7,  8,  8,  8, 10, 11, 13, 13, 13, 14, 17, 19, 19, 19, 20,
       20, 20, 21, 21, 25, 27, 29, 29, 29, 30, 33, 35, 36, 37, 37, 39, 40,
       42, 44, 46, 46, 48, 48])

In [44]:
twoDim = data.reshape(5, 8)
twoDim

array([[ 3,  5,  7,  8,  8,  8, 10, 11],
       [13, 13, 13, 14, 17, 19, 19, 19],
       [20, 20, 20, 21, 21, 25, 27, 29],
       [29, 29, 30, 33, 35, 36, 37, 37],
       [39, 40, 42, 44, 46, 46, 48, 48]])

In [54]:
np.sort(twoDim)

array([[ 3,  5,  7,  8,  8,  8, 10, 11],
       [13, 13, 13, 14, 17, 19, 19, 19],
       [20, 20, 20, 21, 21, 25, 27, 29],
       [29, 29, 30, 33, 35, 36, 37, 37],
       [39, 40, 42, 44, 46, 46, 48, 48]])

In [55]:
twoDim[::-1]

array([[39, 40, 42, 44, 46, 46, 48, 48],
       [29, 29, 30, 33, 35, 36, 37, 37],
       [20, 20, 20, 21, 21, 25, 27, 29],
       [13, 13, 13, 14, 17, 19, 19, 19],
       [ 3,  5,  7,  8,  8,  8, 10, 11]])